name: Auto Merge

on:
  pull_request:

jobs:
  merge-me:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PRESET: DEPENDABOT_MINOR
